//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artists.Subscribers.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopArtistsSubscribers
    {
        public System.Guid Id { get; set; }
        public string SubscriberName { get; set; }
        public string SubscriberEmail { get; set; }
        public Nullable<System.DateTime> SubscribtionDateCreated { get; set; }
    }
}
